# linear regression using multiple variables

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model 
import matplotlib.pyplot as plt

In [6]:
df=pd.read_csv("house_prc.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
import math
x=math.floor(df.bedrooms.median())
x

4

In [15]:
df.bedrooms=df.bedrooms.fillna(x)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
reg=linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [17]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540437

In [20]:
y=df[["area","bedrooms","age"]]
p=reg.predict(y)

In [22]:
df["predict"]=p
df

area  bedrooms  age   price        predict
0  2600       3.0   20  550000  518217.632976
1  3000       4.0   15  565000  602590.079374
2  3200       4.0   18  610000  615307.414037
3  3600       3.0   30  595000  597962.895832
4  4000       5.0    8  760000  760663.426755
5  4100       6.0    8  810000  795258.551027

In [25]:
reg.predict([[3000,3,15]])

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579201.19929613])

# salary prediction using multivariant linear regression

In [71]:
data=pd.read_csv("hiring.csv")
data

experience  test_score  interview_score  salary($)
0        NaN         8.0                9      50000
1        NaN         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [72]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       6 non-null      object 
 1   test_score       7 non-null      float64
 2   interview_score  8 non-null      int64  
 3   salary($)        8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [73]:
data.isnull().sum()

experience         2
test_score         1
interview_score    0
salary($)          0
dtype: int64

In [74]:
med=math.floor(data.test_score.median())
med

8

In [75]:
data.test_score=data.test_score.fillna(med)
data.experience=data.experience.fillna("zero")
# data.experience=data.experience.replace(0,"zero")
data

experience  test_score  interview_score  salary($)
0       zero         8.0                9      50000
1       zero         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         8.0                7      72000
7     eleven         7.0                8      80000

In [76]:
!pip install word2number


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: C:\Users\Dell\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [77]:
from word2number import w2n

In [91]:
data.experience=data.experience.apply(w2n.word_to_num)
data

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         8.0                7      72000
7          11         7.0                8      80000

In [97]:
ref=linear_model.LinearRegression()

ref.fit(data[["experience","test_score","interview_score"]],data["salary($)"])

LinearRegression()

In [99]:
y=data[["experience","test_score","interview_score"]]
f=ref.predict(y)

In [100]:
data["pred_salary"]=f
data

experience  test_score  interview_score  salary($)   pred_salary
0           0         8.0                9      50000  52350.072780
1           0         8.0                6      45000  45734.352256
2           5         6.0                7      60000  58312.954876
3           2        10.0               10      65000  63872.634643
4           7         9.0                6      70000  67270.742358
5           3         7.0               10      62000  61148.471616
6          10         8.0                7      72000  76069.141194
7          11         7.0                8      80000  79241.630277

In [101]:
ref.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [103]:
ref.intercept_

17737.26346433768

In [105]:
ref.predict([[2,9,6]])

C:\Users\Dell\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])